default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railway
  username: postgres
  password: MpSja9AeU3xSkqjIkOho
  host: containers-us-west-176.railway.app
  port: 7619

production:
  <<: *default
  database: railway
  username: postgres
  password: MpSja9AeU3xSkqjIkOho
  host: containers-us-west-176.railway.app
  port: 7619